index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: blog_index
        # make a permanent redirection...
        permanent: true

admin_index:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: admin_blog_index
        # make a permanent redirection...
        permanent: false


rest_controllers:
    resource: '../src/Controller/Rest/'
    type:     annotation
    prefix:   /api
    trailing_slash_on_root: false